theme: jekyll-theme-cayman

baseurl: /bs4-custom-elements

# Setup
title:        bs4-custom-elements
tagline:     Bootstrap components using modern technologies
paginate:     1

# About/contact
author:
  name:       Dimitrios Grammatikogiannis
  url:        https://github.com/dgt41/bs4-custom-elements

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown